/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pract;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.*;
import java.util.Scanner;

/**
 *
 * @author Asus-PC
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public static String filename="E:/testGraph.txt";
    private static String[] a;
   
    
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        butShowGraph = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuOpenFile = new javax.swing.JMenuItem();
        mnuSaveToFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuGenerateGraph = new javax.swing.JMenuItem();

        jFileChooser1.setCurrentDirectory(null);
        jFileChooser1.setDialogTitle("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Алгоритм Флойда-Уоршелла");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        butShowGraph.setText("Показать граф");
        butShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowGraphActionPerformed(evt);
            }
        });

        jLabel1.setText(" Введите матрицу смежности");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Введите число вершин");

        jMenu1.setText("Граф");

        mnuOpenFile.setText("Прочитать из файла...");
        mnuOpenFile.setActionCommand("Открыть");
        mnuOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(mnuOpenFile);

        mnuSaveToFile.setText("Записать в файл...");
        mnuSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveFileActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSaveToFile);
        jMenu1.add(jSeparator1);

        mnuGenerateGraph.setText("Сгенерировать...");
        mnuGenerateGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerateGraphActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGenerateGraph);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butShowGraph))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(butShowGraph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowGraphActionPerformed
        new GraphView().setVisible(true);
    }//GEN-LAST:event_butShowGraphActionPerformed

    private void mnuOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenFileActionPerformed
        jFileChooser1.setDialogTitle("Открыть файл");
        if (jFileChooser1.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                FileInputStream fs = new FileInputStream(file);
                try (Scanner scanner = new Scanner(fs)) {
                    //здесь мы можем использовать разделитель, например: "\\A", "\\Z" или "\\z"
                    String s = scanner.useDelimiter("\\A").next();
                    Alg.Init(s);
                    TableHelper.SetUpTable(jTable1, new TableModelGraph());
                    jTextField1.setText(Alg.N + "");
                }
            } catch (FileNotFoundException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_mnuOpenFileActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String s = jTextField1.getText();
        String S = "";
        int l=s.length();
        String digits = "0123456789";
        for (int i = 0; i < l; i++) {
            char ch = s.charAt(i);
            if (digits.indexOf(ch) >= 0)
                S += ch;
        }
        s=S;
        try{
            int n = Integer.parseInt(s);
            s = "";
            if (n < 2 || n > 20) {
                javax.swing.JOptionPane.showMessageDialog(this, "Количество вершин графа вне диапазона 2...20!");
                return;
            }
            for (int i=0;i<n*n;++i)
            {
                s+="0";
                s+=" ";
            }
        }
        catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Неверно задано количество вершин графа!");
            return;
        }
        Alg.Init(s);
        TableHelper.SetUpTable(jTable1, new TableModelGraph());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String s = "";
        for (int i = 0; i < 100; ++i)
            s += "0 ";
        
        Alg.Init(s);
        TableHelper.SetUpTable(jTable1, new TableModelGraph());
    }//GEN-LAST:event_formWindowOpened

    private void mnuGenerateGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerateGraphActionPerformed
        // TODO add your handling code here:
        Gen g = new Gen();
        g.setVisible(true);
        g.addWindowListener(new WindowListener() {
            @Override
            public void windowClosed(WindowEvent e) {

                if (g.I == 1) {
                    TableHelper.SetUpTable(jTable1, new TableModelGraph());
                    jTable1.repaint();
                    GraphView.main(a);
                }
            }

            @Override
            public void windowOpened(WindowEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowClosing(WindowEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowIconified(WindowEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowActivated(WindowEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }//GEN-LAST:event_mnuGenerateGraphActionPerformed

    private void mnuSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveFileActionPerformed
        jFileChooser1.setDialogTitle("Сохранить файл");
        if (jFileChooser1.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                FileOutputStream fs = new FileOutputStream(file);
                try (PrintWriter writer = new PrintWriter(fs)) {
                    for (int i = 0; i < Alg.N; i++) {
                        for (int j = 0; j < Alg.N; j++)
                            writer.print(Alg.L[i][j] + " ");
                        writer.println();
                    }
                }
            } catch (FileNotFoundException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_mnuSaveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
        a = args;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butShowGraph;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mnuGenerateGraph;
    private javax.swing.JMenuItem mnuOpenFile;
    private javax.swing.JMenuItem mnuSaveToFile;
    // End of variables declaration//GEN-END:variables
}
